# Generated by Django 4.0.2 on 2022-02-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=25)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Фэнтези', 'Фэнтези'), ('Боевик', 'Боевик'), ('Драма', 'Драма'), ('Роман', 'Роман'), ('Комедия', 'Комедия')], max_length=70)),
                ('pages', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
