# Generated by Django 4.0.2 on 2022-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0002_showcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcomment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
