# Generated by Django 4.0.2 on 2022-02-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0004_book_detail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_detail',
            name='image',
        ),
    ]
