# Generated by Django 4.0.2 on 2022-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_detail', '0005_remove_book_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
